version: '3.1'

services:
  postgresql:
    container_name: postregsql_gym
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
      POSTGRES_DB: gym
    networks:
    - gym-network
    ports:
    - 5433:5432
    volumes:
    - ./dbfiles:/docker-entrypoint-initdb.d
    -  /var/lib/postgres_data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbit_mq_gym
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: gym
      RABBITMQ_DEFAULT_PASS: gym
      RABBITMQ_DEFAULT_VHOST: gym
    ports:
    - 5672:5672
    networks:
    - gym-network
    volumes:
    - ./rabbitmq_info:/var/lib/rabbitmq
    - ./config_rabbit_mq:/etc/rabbitmq/rabbitmq.config
  mongodb:
    container_name: mongo_db_gym
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "gym"
      MONGO_INITDB_ROOT_PASSWORD: "gym"
    networks:
      - gym-network
networks:
  gym-network: